### ISSUE TITLE
Do we need to check if Pro7 is running?

### ISSUE THREAD

**Issue by arlinsandbulte** [greyshirtguy/Pro7-Media-Sweeper#1]
From your readme to-do list:
#Do we need to check if Pro7 is running? (Is it always okay to open and read all the docs and playlists while Pro7 is running?)

That might be a good idea, but not necessary IMO.
This script should just read the Propresenter files and not alter them.
And, any media files that get moved should not be used any way, so that should not mess Pro7.

So, IMO, it might be good practice, But we don't need to worry about it yet in the early stages of development.
Once the core functionality is implemented, this feature could be revisited.

**Comment by greyshirtguy** [comment]
I imagine you are correct.  I was flagging that to handle possibility that Pro7 *might* open a with exclusive file access.  File locking is not common or likely - but if it did (eg say a playlist)...then we would not be able to read it!
Potential impact might be removing files that *are* referenced by the locked playlist file.

Again - not likely - just flagging the slim possibility (and there's no way to know 100% that won't change in future updates)

**Comment by greyshirtguy** [comment]
I can't see any evidence of Pro7 locking any of its docs or config files...
Closing issue **without** adding any logic to make sure Pro7 is not running.
